feat: gateway-api package added
glasskube/packages pull request #155
Opened 2024-06-18 13:41 UTC by bishalbera

Closes [#764](https://github.com/glasskube/glasskube/issues/764)

### Description

Adding a new package called gateway-api

2024-06-18 13:45 UTC, bishalbera commented
@christophenne So, now can I work on a different issue?

2024-06-18 15:24 UTC, christophenne commented
> @christophenne So, now can I work on a different issue?

If you want, you can of course also try to debug the operator and check whether the redirect problem is the actual problem (that was just a guess by me). Maybe it's also something else.

2024-07-04 12:05 UTC, christophenne commented
This is blocked by https://github.com/glasskube/glasskube/issues/952

2024-07-08 09:31 UTC, christophenne requested changes

2024-07-08 09:31 UTC, christophenne commented on packages/gateway-api/v1.1.0/package.yaml
> +  - url: https://objects.githubusercontent.com/github-production-release-asset-2e65be/219058535/32e6db11-1a9d-4159-9f74-ac18d09024ce?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=releaseassetprod
Please change the manifest url back to `https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.1.0/standard-install.yaml`

2024-07-08 09:31 UTC, christophenne commented on packages/gateway-api/v1.1.0/package.yaml
> +defaultNamespace: "gateway-api-system"
Not sure about this, it seems to me that this package only installs CRDs right? In that case, I think the `defaultNamespace` can be removed. I also tried installing the package, the namespace is not being created.

2024-07-08 09:31 UTC, christophenne commented on packages/index.yaml
> +  - iconUrl: "https://avatars.githubusercontent.com/u/36015203"
Please remove the changes to this file, as it will be updated automatically by our pipeline.

2024-07-08 10:03 UTC, bishalbera commented
@christophenne made those changes . Check now please

2024-07-08 11:34 UTC, christophenne commented
> @christophenne made those changes . Check now please

Thanks, one last thing that would be nice is if you could squash the two commits and change the message to `feat(gateway-api): initial support`, since we don't have the Github merge queue in this repository. Other than that it looks good to me.

2024-07-08 12:08 UTC, bishalbera commented
@christophenne Please check is it ok?

2024-07-08 12:09 UTC, christophenne commented
> @christophenne Please check is it ok?

yes, thank you

2024-07-08 12:15 UTC, bishalbera commented
> > @christophenne Please check is it ok?
> 
> yes, thank you

ok, Nice

2024-07-09 08:28 UTC, christophenne approved these changes

2024-07-09 09:04 UTC, kosmoz commented
Maybe we should extend the description to clarify that this package only includes the CRDs and a compatible controller must be installed separately? I think otherwise it might be confusing to someone now knowing what this is…

2024-07-09 09:05 UTC, kosmoz requested changes

2024-07-09 09:05 UTC, kosmoz commented on packages/gateway-api/v1.1.0/package.yaml
Please add a default namespace. It doesn't do anything for this package but it is required by the schema

2024-07-09 11:05 UTC, bishalbera commented on packages/gateway-api/v1.1.0/package.yaml
@kosmoz added check now please .

2024-07-09 13:13 UTC, kosmoz requested changes

2024-07-09 13:13 UTC, kosmoz commented on packages/gateway-api/v1.1.0/package.yaml
> +  The Gateway API is a Kubernetes extension that standardizes the configuration and management of network traffic routing. It introduces new resource types like Gateway, GatewayClass, and HTTPRoute t
```suggestion
  The Gateway API is a Kubernetes extension that standardizes the configuration and management of network traffic routing.
  It introduces new resource types like Gateway, GatewayClass, and HTTPRoute to provide flexible and extensible traffic control.
  This API enables better separation of concerns and more robust traffic management in Kubernetes environments.

  > **Note:** This package installs the Gateway API CRDs from the official source.
    To utilize them, install a controller implementing this API.
    You can find a list of implementations [here](https://gateway-api.sigs.k8s.io/implementations/).
```

2024-07-09 13:14 UTC, kosmoz commented
Note: v0.13.0 has been released, which includes the fix required for this package.

https://github.com/glasskube/glasskube/releases/tag/v0.13.0

2024-07-10 00:57 UTC, bishalbera commented
> Note: v0.13.0 has been released, which includes the fix required for this package.
> 
> https://github.com/glasskube/glasskube/releases/tag/v0.13.0

Ya I saw that . Thanks :)

2024-07-10 08:21 UTC, kosmoz approved these changes

2024-07-10 08:21 UTC, merged