feat(headlamp): add initial headlamp support
glasskube/packages pull request #176
Opened 2024-06-27 15:34 UTC by pmig

2024-06-28 08:43 UTC, kosmoz requested changes

2024-06-28 08:43 UTC, kosmoz commented on packages/headlamp/v0.24.0+1/package.yaml
> +  To log in to the Headlamp Dashboard, you need to generate a token for the Kubernetes Dashboard.
```suggestion
  To log in to the Headlamp Dashboard, you need to generate an authentication token first.
```

2024-06-28 08:43 UTC, kosmoz commented on packages/headlamp/v0.24.0+1/package.yaml
> +  Glasskube creates a dashboard user. You can generate a token to log in via:
```suggestion
  Glasskube creates a dedicated service account for this purpose. You can generate a token to log in via:
```

2024-06-28 08:43 UTC, kosmoz commented on packages/headlamp/v0.24.0+1/package.yaml
add scope please

2024-07-09 12:36 UTC, kosmoz approved these changes

2024-07-09 12:37 UTC, kosmoz commented
@pmig I took the liberty and finished this PR. Feel free to merge if you approve the changes I made, or otherwise make further changes.

2024-07-09 14:38 UTC, pmig reviewed
If possible packages should be namespaced

2024-07-09 14:38 UTC, pmig commented on packages/headlamp/v0.24.0+1/package.yaml
> +scope: Cluster
As headlamp has no CRD it could be namespaced, as some hosted cases could similar to quickwit could be possible?

2024-07-09 14:42 UTC, pmig commented on packages/headlamp/v0.24.0+1/package.yaml
> +scope: Cluster
nevermind it has a cluster role binding so it needs to stay cluster: https://github.com/headlamp-k8s/headlamp/blob/main/charts/headlamp/templates/clusterrolebinding.yaml

2024-07-09 14:54 UTC, merged