feat(temporal): initial support
glasskube/packages pull request #391
Opened 2024-09-09 13:25 UTC by kosmoz

2024-09-12 06:24 UTC, pmig commented
@kosmoz I talked with @robholland about the upstream pr. He is eager to merge it, but as he is traveling it will take at least one more week. In the meantime we should either deploy the helm chart to the glasskube charts repo or build the chart and push it to an oci registry so we are not blocked by the upstream.

2024-09-12 11:02 UTC, kosmoz commented
@pmig OK thanks, a version of the chart that includes the TTL and default namespace features is now available on charts.glasskube.eu

@christophenne can you check if the package works for you use case?

2024-09-13 06:59 UTC, pmig requested changes

2024-09-13 06:59 UTC, pmig commented on packages/temporal/v1.25.0+1/package.yaml
> +scope: Namespaced
```suggestion
scope: Namespaced
iconUrl: https://avatars.githubusercontent.com/u/56493103
```

2024-09-13 06:59 UTC, pmig commented on packages/temporal/v1.25.0+1/package.yaml
> +scope: Namespaced
NIT: but an icon makes it so much better :-)

2024-09-13 22:41 UTC, pmig submitted a review, later dismissed

2024-09-13 23:53 UTC, merged